apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: edge-nginx
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    # path to the folder with the YAML manifests
    path: manifests 
    repoURL: https://github.com/kgamanji/kube-edge-argocd-demo 
    targetRevision: HEAD
  # Sync policy
  syncPolicy:
    automated: {}
