apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: edge-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image:  nginx:1.20.1 #alpine
        imagePullPolicy: IfNotPresent
        name: edge-nginx
